name: Check markdown format

on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # same as npx prettier --check ./content/**/*.md
          # if ci failed, try to run `npx prettier --write ./content/**/*.md` to fix it
          prettier_options: --check ./content/**/*.md
